// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Claritas",
    defaultLocalization: "en",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Claritas",
            targets: ["Claritas"],
            bundleIdentifier: "com.claritas.app",
            teamIdentifier: "Z3GU26J2H4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .education,
            additionalInfoPlistContentFilePath: "Sources/Claritas/Support/AdditionalInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "Claritas",
            path: "Sources/Claritas",
            resources: [
                .process("Assets.xcassets")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)